name: ArchWallet
targets:
  ArchWallet:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.archwallet.app
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
    sources:
      - path: .
